### ISSUE TITLE
release on pypi

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/ontorunner#9]
may need to choose a new name as there are runners on pypi already

ideas for names? @turbomam @deepakunni3 @realmarcin @hrshdhgd ?

**Comment by realmarcin** [comment]
For now I will throw this one in:

wranNER
or
wraNER

(though I think pypi packages are case insensitive)

meaning a 'wrapper package for NER tools'

**Comment by hrshdhgd** [comment]
Another option could be ontoNER ?

**Comment by deepakunni3** [comment]
Couple of suggestions:
- concept-miner
- definer 
- pontonier/pontoneer

**Comment by hrshdhgd** [comment]
Fixed by #38
